{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "from flask import Flask, request\n",
    "from flask_cors import CORS, cross_origin\n",
    "from flask_restful import Resource, Api\n",
    "from json import dumps\n",
    "from flask_jsonpify import jsonify\n",
    "import json\n",
    "from collections import Counter\n",
    "import requests"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "with open(\"./metric.json\") as f:\n",
    "    data=json.load(f)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 41,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<flask_cors.extension.CORS at 0x112cc3d10>"
      ]
     },
     "execution_count": 41,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "app = Flask(__name__)\n",
    "api = Api(app)\n",
    "CORS(app)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 42,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "@app.route(\"/hello\")\n",
    "def hello():\n",
    "    return jsonify({'text':'Hello World!'})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "metadata": {},
   "outputs": [],
   "source": [
    "@app.route(\"/getMetric\",methods=['GET'])\n",
    "def getMetric():\n",
    "    return  jsonify({'data':data})\n",
    "\n",
    "\n",
    "@app.route(\"/saveMetric\",methods=['POST'])\n",
    "def saveMetricData():\n",
    "    params=request.get_json(silent=True)\n",
    "    print(params[\"data\"])\n",
    "    with open(\"./metric.json\",'w') as f:\n",
    "        result=json.dump(data,f)\n",
    "    \n",
    "    return  jsonify({'response':'Metric saved successfully'})\n",
    "\n",
    "\n",
    "@app.route(\"/getUser\",methods=['POST'])\n",
    "def getUser():\n",
    "    params=request.get_json(silent=True)\n",
    "    username=params[\"userName\"]\n",
    "    try:\n",
    "        with open(\"./Users/\"+username+\".json\") as f:\n",
    "            data=json.load(f)\n",
    "        return  jsonify({'userProfile':data})\n",
    "    except:\n",
    "        return jsonify({'userProfile':{}}),400\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "   WARNING: This is a development server. Do not use it in a production deployment.\n",
      "   Use a production WSGI server instead.\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://127.0.0.1:5005/ (Press CTRL+C to quit)\n",
      "127.0.0.1 - - [18/Jan/2020 16:08:10] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "[2020-01-18 16:08:10,278] ERROR in app: Exception on /getUser [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask_cors/extension.py\", line 161, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask_restful/__init__.py\", line 269, in error_router\n",
      "    return original_handler(e)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-43-ae2895145476>\", line 19, in getUser\n",
      "    username=params[\"userName\"]\n",
      "KeyError: 'userName'\n",
      "127.0.0.1 - - [18/Jan/2020 16:08:10] \"POST /getUser HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:09:26] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "[2020-01-18 16:09:26,786] ERROR in app: Exception on /getUser [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask_cors/extension.py\", line 161, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask_restful/__init__.py\", line 269, in error_router\n",
      "    return original_handler(e)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-43-ae2895145476>\", line 21, in getUser\n",
      "    data=json.load(f)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/json/__init__.py\", line 291, in load\n",
      "    **kw)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/json/__init__.py\", line 339, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/json/decoder.py\", line 364, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/json/decoder.py\", line 380, in raw_decode\n",
      "    obj, end = self.scan_once(s, idx)\n",
      "ValueError: Expecting property name: line 13 column 1 (char 200)\n",
      "127.0.0.1 - - [18/Jan/2020 16:09:26] \"POST /getUser HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:10:00] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:10:01] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:11:28] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:11:28] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:13:13] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:13:13] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:13:16] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:13:42] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:13:42] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:14:01] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:14:02] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:14:18] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:14:18] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:14:22] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:15:23] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "[2020-01-18 16:15:23,637] ERROR in app: Exception on /getUser [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask_cors/extension.py\", line 161, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask_restful/__init__.py\", line 269, in error_router\n",
      "    return original_handler(e)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-43-ae2895145476>\", line 20, in getUser\n",
      "    with open(\"./Users/\"+username+\".json\") as f:\n",
      "TypeError: cannot concatenate 'str' and 'NoneType' objects\n",
      "127.0.0.1 - - [18/Jan/2020 16:15:23] \"POST /getUser HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:17:03] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:17:03] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:17:07] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:17:08] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:17:09] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:17:43] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:17:43] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:18:05] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:18:05] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:18:07] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:23:32] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "[2020-01-18 16:23:32,423] ERROR in app: Exception on /getUser [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask_cors/extension.py\", line 161, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask_restful/__init__.py\", line 269, in error_router\n",
      "    return original_handler(e)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-43-ae2895145476>\", line 21, in getUser\n",
      "    data=json.load(f)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/json/__init__.py\", line 291, in load\n",
      "    **kw)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/json/__init__.py\", line 339, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/json/decoder.py\", line 364, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/json/decoder.py\", line 380, in raw_decode\n",
      "    obj, end = self.scan_once(s, idx)\n",
      "ValueError: Expecting property name: line 18 column 1 (char 269)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [18/Jan/2020 16:23:32] \"POST /getUser HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:23:55] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "[2020-01-18 16:23:55,755] ERROR in app: Exception on /getUser [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask_cors/extension.py\", line 161, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask_restful/__init__.py\", line 269, in error_router\n",
      "    return original_handler(e)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-43-ae2895145476>\", line 21, in getUser\n",
      "    data=json.load(f)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/json/__init__.py\", line 291, in load\n",
      "    **kw)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/json/__init__.py\", line 339, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/json/decoder.py\", line 364, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/json/decoder.py\", line 380, in raw_decode\n",
      "    obj, end = self.scan_once(s, idx)\n",
      "ValueError: Expecting property name: line 18 column 1 (char 269)\n",
      "127.0.0.1 - - [18/Jan/2020 16:23:55] \"POST /getUser HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:24:11] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "[2020-01-18 16:24:11,467] ERROR in app: Exception on /getUser [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask_cors/extension.py\", line 161, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask_restful/__init__.py\", line 269, in error_router\n",
      "    return original_handler(e)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-43-ae2895145476>\", line 21, in getUser\n",
      "    data=json.load(f)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/json/__init__.py\", line 291, in load\n",
      "    **kw)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/json/__init__.py\", line 339, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/json/decoder.py\", line 364, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/json/decoder.py\", line 380, in raw_decode\n",
      "    obj, end = self.scan_once(s, idx)\n",
      "ValueError: Expecting property name: line 18 column 1 (char 269)\n",
      "127.0.0.1 - - [18/Jan/2020 16:24:11] \"POST /getUser HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:24:38] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:24:39] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:26:09] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "[2020-01-18 16:26:09,051] ERROR in app: Exception on /getUser [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask_cors/extension.py\", line 161, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask_restful/__init__.py\", line 269, in error_router\n",
      "    return original_handler(e)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-43-ae2895145476>\", line 20, in getUser\n",
      "    with open(\"./Users/\"+username+\".json\") as f:\n",
      "TypeError: cannot concatenate 'str' and 'NoneType' objects\n",
      "127.0.0.1 - - [18/Jan/2020 16:26:09] \"POST /getUser HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:26:12] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:26:15] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:26:15] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:28:41] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:28:41] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:31:39] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:31:39] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:31:53] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:31:53] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:32:14] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:32:14] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:32:32] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:32:33] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:32:44] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:32:45] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:33:06] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:33:07] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:33:50] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:33:50] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:34:19] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:34:19] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:34:55] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:34:55] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:35:07] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:35:07] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:36:00] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:36:01] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:36:11] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:36:11] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:36:38] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:36:38] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:38:52] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:38:52] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:39:28] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:39:28] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:39:28] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:39:28] \"POST /getUser HTTP/1.1\" 200 -\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [18/Jan/2020 16:40:26] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:40:26] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:40:43] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:40:43] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:41:04] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:41:04] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:45:56] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:45:56] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:46:03] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:46:03] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:46:17] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:46:17] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:48:11] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:48:12] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:48:24] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:48:24] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:48:46] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:48:46] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:50:16] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:50:16] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:50:39] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:50:40] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:51:07] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:51:07] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:51:38] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:51:39] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:52:06] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:52:06] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:52:25] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:52:25] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:53:28] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:53:28] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:53:41] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:53:41] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:54:23] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "[2020-01-18 16:54:23,053] ERROR in app: Exception on /getUser [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask_cors/extension.py\", line 161, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask_restful/__init__.py\", line 269, in error_router\n",
      "    return original_handler(e)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-43-ae2895145476>\", line 21, in getUser\n",
      "    data=json.load(f)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/json/__init__.py\", line 291, in load\n",
      "    **kw)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/json/__init__.py\", line 339, in loads\n",
      "    return _default_decoder.decode(s)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/json/decoder.py\", line 364, in decode\n",
      "    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/json/decoder.py\", line 380, in raw_decode\n",
      "    obj, end = self.scan_once(s, idx)\n",
      "ValueError: Expecting , delimiter: line 5 column 5 (char 89)\n",
      "127.0.0.1 - - [18/Jan/2020 16:54:23] \"POST /getUser HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:54:31] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:54:31] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:55:47] \"GET /getMetric HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:55:54] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:55:54] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:55:56] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:56:02] \"GET /getMetric HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:56:06] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "[2020-01-18 16:56:06,117] ERROR in app: Exception on /getUser [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask_cors/extension.py\", line 161, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask_restful/__init__.py\", line 269, in error_router\n",
      "    return original_handler(e)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-43-ae2895145476>\", line 20, in getUser\n",
      "    with open(\"./Users/\"+username+\".json\") as f:\n",
      "TypeError: cannot concatenate 'str' and 'NoneType' objects\n",
      "127.0.0.1 - - [18/Jan/2020 16:56:06] \"POST /getUser HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:56:08] \"GET /getMetric HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:56:09] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:56:10] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:57:52] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:57:52] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:58:15] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 16:58:15] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 17:01:32] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 17:01:32] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 17:02:20] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 17:02:20] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 17:02:43] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 17:02:43] \"POST /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 17:03:08] \"OPTIONS /getUser HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [18/Jan/2020 17:03:08] \"POST /getUser HTTP/1.1\" 200 -\n",
      "[2020-01-18 17:03:11,843] ERROR in app: Exception on /getUser [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask_cors/extension.py\", line 161, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask_restful/__init__.py\", line 269, in error_router\n",
      "    return original_handler(e)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/hemanth/anaconda2/lib/python2.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-43-ae2895145476>\", line 20, in getUser\n",
      "    with open(\"./Users/\"+username+\".json\") as f:\n",
      "IOError: [Errno 2] No such file or directory: u'./Users/sadxsacd.json'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [18/Jan/2020 17:03:11] \"POST /getUser HTTP/1.1\" 500 -\n"
     ]
    }
   ],
   "source": [
    "if __name__ == '__main__':\n",
    "   app.run(port=5005)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 2",
   "language": "python",
   "name": "python2"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.15"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
